INSERT INTO states (codigo_uf, name, abbreviation, updated_at)
VALUES
  (12, 'Acre', 'AC', NOW()),
  (27, 'Alagoas', 'AL', NOW()),
  (16, 'Amapa', 'AP', NOW()),
  (13, 'Amazonas', 'AM', NOW()),
  (29, 'Bahia', 'BA', NOW()),
  (23, 'Ceara', 'CE', NOW()),
  (53, 'Distrito Federal', 'DF', NOW()),
  (32, 'Espirito Santo', 'ES', NOW()),
  (52, 'Goias', 'GO', NOW()),
  (21, 'Maranhao', 'MA', NOW()),
  (51, 'Mato Grosso', 'MT', NOW()),
  (50, 'Mato Grosso do Sul', 'MS', NOW()),
  (31, 'Minas Gerais', 'MG', NOW()),
  (15, 'Para', 'PA', NOW()),
  (25, 'Paraiba', 'PB', NOW()),
  (41, 'Parana', 'PR', NOW()),
  (26, 'Pernambuco', 'PE', NOW()),
  (22, 'Piaui', 'PI', NOW()),
  (33, 'Rio de Janeiro', 'RJ', NOW()),
  (24, 'Rio Grande do Norte', 'RN', NOW()),
  (43, 'Rio Grande do Sul', 'RS', NOW()),
  (11, 'Rondonia', 'RO', NOW()),
  (14, 'Roraima', 'RR', NOW()),
  (42, 'Santa Catarina', 'SC', NOW()),
  (35, 'Sao Paulo', 'SP', NOW()),
  (28, 'Sergipe', 'SE', NOW()),
  (17, 'Tocantins', 'TO', NOW())
ON CONFLICT (codigo_uf) DO NOTHING;
